with open("frontend/src/api/system/menu.js", "w", encoding="utf-8") as f:
    f.write("""import request from \'@/utils/request\'\n\n""")
    f.write("""export function getMenuList(params) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/menu/list',\n""")
    f.write("""    method: 'get',\n""")
    f.write("""    params\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function getMenuTree(params) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/menu/tree',\n""")
    f.write("""    method: 'get',\n""")
    f.write("""    params\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function getMenuInfo(menuId) {\n""")
    f.write("""  return request({\n""")
    f.write('    url: `/system/menu/${menuId}`,\n')
    f.write("""    method: 'get'\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function addMenu(data) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/menu',\n""")
    f.write("""    method: 'post',\n""")
    f.write("""    data\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function updateMenu(data) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/menu',\n""")
    f.write("""    method: 'put',\n""")
    f.write("""    data\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function deleteMenu(id) {\n""")
    f.write("""  return request({\n""")
    f.write('    url: `/system/menu/${id}`,\n')
    f.write("""    method: 'delete'\n""")
    f.write("""  })\n""")
    f.write("""}\n""")
print("done")
