with open("frontend/src/api/system/role.js", "w", encoding="utf-8") as f:
    f.write("""import request from \'@/utils/request\'\n\n""")
    f.write("""export function getRoleList(params) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/role/list',\n""")
    f.write("""    method: 'get',\n""")
    f.write("""    params\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function getRoleInfo(roleId) {\n""")
    f.write("""  return request({\n""")
    f.write('    url: `/system/role/${roleId}`,\n')
    f.write("""    method: 'get'\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function addRole(data) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/role',\n""")
    f.write("""    method: 'post',\n""")
    f.write("""    data\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function updateRole(data) {\n""")
    f.write("""  return request({\n""")
    f.write("""    url: '/system/role',\n""")
    f.write("""    method: 'put',\n""")
    f.write("""    data\n""")
    f.write("""  })\n""")
    f.write("""}\n\n""")
    f.write("""export function deleteRole(id) {\n""")
    f.write("""  return request({\n""")
    f.write('    url: `/system/role/${id}`,\n')
    f.write("""    method: 'delete'\n""")
    f.write("""  })\n""")
    f.write("""}\n""")
print("done")
