-- 收费管理模块表结构

-- 创建收费项目表
CREATE TABLE fee_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    item_name VARCHAR(100) NOT NULL COMMENT '收费项目名称',
    price DECIMAL(10,2) NOT NULL COMMENT '单价',
    cycle_type TINYINT NOT NULL COMMENT '收费周期：1月 2季 3年',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0禁用 1启用',
    remark VARCHAR(500) COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '收费项目表';

-- 创建缴费账单记录表
CREATE TABLE fee_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL COMMENT '业主id',
    house_id BIGINT NOT NULL COMMENT '房屋id',
    item_id BIGINT NOT NULL COMMENT '收费项目id',
    total_money DECIMAL(10,2) NOT NULL COMMENT '应付总金额',
    bill_cycle VARCHAR(20) NOT NULL COMMENT '账单所属周期（如：2024-01）',
    pay_status TINYINT NOT NULL DEFAULT 0 COMMENT '缴费状态：0未缴费 1已缴费 2欠费',
    pay_time DATETIME COMMENT '实际缴费时间',
    pay_way VARCHAR(50) COMMENT '支付方式',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) COMMENT '缴费账单记录表';